version: '3.8'
services:
  backend:
    build:
      context: ./PaiNaiDee_Backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=docker
      - DB_HOST=db
      - DB_NAME=painaidee_db
      - DB_USER=postgres
      - DB_PASSWORD=Got0896177698
      - DB_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "
        pip install psycopg2-binary &&
        python init_db.py &&
        python migrate_image_urls.py &&
        python run.py
      "

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=painaidee_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Got0896177698
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./pai-naidee-ui-spark
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: