version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      - FLASK_ENV=docker
      - DB_HOST=db
      - DB_NAME=painaidee_db
      - DB_USER=postgres
      - DB_PASSWORD=Got0896177698
      - DB_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "
        pip install psycopg2-binary &&
        python init_db.py &&
        python migrate_image_urls.py &&
        python run_fastapi.py
      "

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=painaidee_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Got0896177698
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./pai-naidee-ui-spark
    ports:
      - "80:80"
    depends_on:
      - backend

  map3d:
    build:
      context: ./PaiNaiDee_map_3D
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  ai_assistant:
    build:
      context: https://github.com/athipan1/AI_Assistant_PaiNaiDee.git
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

volumes:
  postgres_data: