version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=docker
      - DB_HOST=painaidee
      - DB_NAME=painaidee_db
      - DB_USER=postgres
      - DB_PASSWORD=Got0896177698
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13
    hostname: painaidee
    environment:
      - POSTGRES_DB=painaidee_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Got0896177698
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
