"""Add source and timestamp fields to attractions

Revision ID: 8d0e51c829d4
Revises: 001_phase1_models
Create Date: 2025-09-07 14:50:18.814475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0e51c829d4'
down_revision: Union[str, None] = '001_phase1_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attractions', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('attractions', sa.Column('source_id', sa.String(length=255), nullable=True))
    op.add_column('attractions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('attractions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint('uq_attraction_source_source_id', 'attractions', ['source', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attraction_source_source_id', 'attractions', type_='unique')
    op.drop_column('attractions', 'updated_at')
    op.drop_column('attractions', 'created_at')
    op.drop_column('attractions', 'source_id')
    op.drop_column('attractions', 'source')
    # ### end Alembic commands ###
