name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5433:5432
        # Options to wait for the DB to be ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          # Install psycopg2 to connect to postgres
          pip install psycopg2-binary

      - name: Run Flask app tests
        env:
          # Tell the app to use the PostgreSQL DB from the service container
          CI: true
          DB_HOST: localhost
          DB_PORT: 5433
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: test_db
        run: |
          source venv/bin/activate
          python -m pytest